version: '3.7'

services:
    ### MONGO ###############################################
    mongo:
        image: mongo:4.4.4-bionic
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=base_admin
            - MONGO_INITDB_ROOT_PASSWORD=base_admin
            - MONGO_INITDB_DATABASE=base_db
        ports:
            - 27017:27017
        volumes:
            - ./data/mongo:/data/db
        container_name: mongo

    ### postgres ###############################################
    postgres:
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=base_admin
            - POSTGRES_PASSWORD=base_admin
            - POSTGRES_DB=base_db
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - 5432:5432
        volumes:
            - ./data/postgres:/data/postgres
        container_name: postgres

    ### ELASTICSEARCH #######################################
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
        restart: always
        environment:
            - discovery.type=single-node
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - cluster.routing.allocation.disk.threshold_enabled=true
            - cluster.routing.allocation.disk.watermark.low=2gb
            - cluster.routing.allocation.disk.watermark.high=1gb
            - cluster.routing.allocation.disk.watermark.flood_stage=512mb
            - ES_JAVA_OPTS=-Xms500m -Xmx500m
        ports:
            - 9200:9200
        volumes:
            - ./data/elasticsearch:/usr/share/elasticsearch/data
        container_name: elasticsearch

    ### KIBANA #######################################
    kibana:
        image: docker.elastic.co/kibana/kibana:7.11.1
        restart: always
        environment:
            - SERVER_NAME=localhost
            - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
            - xpack.security.enabled=false
        depends_on:
            - elasticsearch
        ports:
            - 5601:5601
        container_name: kibana
    ### PGADMIN ###############################################
    pgadmin:
        image: dpage/pgadmin4
        depends_on:
            - postgres
        ports:
            - '5555:80'
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped
        container_name: pgadmin
volumes:
    data:
        driver: local
networks:
    local:
        driver: bridge
